### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by deitch** [packethost/packet-nodejs#20]
Looks great, but any plans to publish to npm?

````
$ npm install --save packet-nodes
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/packet-nodejs
npm ERR! 404
npm ERR! 404  'packet-nodejs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
````

**Comment by dkenzox** [comment]
@deitch I just published the library, can you check if everything works fine for you?

**Comment by deitch** [comment]
````
$ npm install packet-nodes
.... installs
$ npm ls packet-nodejs
└── packet-nodejs@0.0.1
````

Looks good to me!

I had to patch it to work with finding IPs and assigning IPs. I will have a PR here sometime next week, when I can find time.

Thanks @dkenzox !

**Comment by dkenzox** [comment]
@deitch I added a few IPs methods to this library yesterday for projects, devices(you can see them in the readme), did you have to patch those to have them working? If so I would love to know what I can do to help you have it working.

**Comment by deitch** [comment]
@dkenzox yes, that is it. My augmentation of it in my project used `.assignIp()` and `getProjectIpReservations()` (although I had called it `getProjectIps()`. Looks great to me.
