### ISSUE TITLE
Please fix your library docs

### ISSUE THREAD

**Issue by ysset** [packethost/packet-nodejs#29]
I just see this in lib docs, but it doesn't work like add or create new device or server.
![image](https://user-images.githubusercontent.com/52471762/119280822-36be9a80-bc87-11eb-845e-224935bf2a81.png)
i found a misstake.
![image](https://user-images.githubusercontent.com/52471762/119281664-9d918300-bc8a-11eb-9ddd-6fcf2f3d1b35.png)

**Comment by jacobsmith928** [comment]
@ysset this library hasn't been updated in a while - we are focusing attention on our Go library (due to Terraform integration) and a few others.  We'll take a look at these issues as we can, and certainly review any PR's.
